eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8070

spring:
  application:
    name: schools #The same name as the file yml in the config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/schoolsdb?createDatabaseIfNotExist=true
    username: postgres
    password: mimi019mimi
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    database: postgresql

application:
  config:
    #To use the gateway for communication bewteen the services
    students-url: http://localhost:8222/students
    #To ensure communication between the services directly within the same network
    #students-url: http://localhost:8090/students


management:
  tracing:
    sampling:
      probability: 1.0