eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  application:
    name: students #The same name as the file yml in the config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/studentsdb?createDatabaseIfNotExist=true
    username: postgres
    password: mimi019mimi
    driver-class-name: org.postgresql.Driver



  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    database: postgresql
management:
  tracing:
    sampling:
        probability: 1.0