server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native: #Where the configuration files are located
          search-locations: classpath:/configurations